name: CI-CD to AKS

on:
  push:
    branches:
      - main

env:
  ACR_NAME: aksdevopsacr12345
  IMAGE_NAME: aks-demo
  RESOURCE_GROUP: aks-devops-rg
  AKS_CLUSTER: aks-devops-cluster

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to ACR
      run: az acr login --name $ACR_NAME

    - name: Build Docker Image
      run: |
        docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }} ./app

    - name: Push Docker Image
      run: |
        docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }}

    - name: Set AKS context
      run: |
        az aks get-credentials --resource-group $RESOURCE_GROUP --name $AKS_CLUSTER

    - name: Deploy to AKS
      run: |
        kubectl set image deployment/aks-demo aks-demo=$ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }}
