apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aks-demo
  template:
    metadata:
      labels:
        app: aks-demo
    spec:
      containers:
      - name: aks-demo
        image: <your-acr-name>.azurecr.io/aks-demo:v1
        ports:
        - containerPort: 5000
