apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secret
spec:
  provider: azure
  parameters:
    useManagedIdentity: "true"
    keyvaultName: "aks-devops-kv"   # same as Terraform
    tenantId: "<YOUR-TENANT-ID>"
    objects: |
      array:
        - |
          objectName: APP-MESSAGE
          objectType: secret
