apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secret
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"   
    userAssignedIdentityID: "47279f90-27a6-464c-8764-068694c64fda"     
    keyvaultName: "aks-devops-kv"
    objects: |
      array:
        - |
          objectName: APP-MESSAGE
          objectType: secret
    tenantId: "8afe33fb-7e35-43bb-8e3a-e9c573d64c34"
