apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secret
spec:
  provider: azure
  parameters:
    useManagedIdentity: "true"
   
    userAssignedIdentityID: ""

    keyvaultName: "aks-devops-kv"
    tenantId: "d5521bfd-0210-4d7b-9102-b08a9ae41cb3"

    objects: |
      array:
        - |
          objectName: APP-MESSAGE
          objectType: secret

  secretObjects:
  - secretName: azure-kv-secret
    type: Opaque
    data:
    - objectName: APP-MESSAGE
      key: APP-MESSAGE
